#!/bin/bash
# Helper script to copy users from production to staging
# This provides step-by-step instructions

echo "📋 Copy Users from Production to Staging"
echo "========================================"
echo ""
echo "This process has 3 steps:"
echo ""
echo "STEP 1: Export users from PRODUCTION"
echo "------------------------------------"
echo "1. Go to your PRODUCTION Supabase Dashboard"
echo "2. Open SQL Editor"
echo "3. Run the query from: scripts/export-users-from-prod.sql"
echo "4. Copy the results (CSV or JSON format)"
echo ""
echo "STEP 2: Create auth.users in STAGING"
echo "------------------------------------"
echo "Option A: Via Dashboard (easiest)"
echo "  1. Go to: https://supabase.com/dashboard/project/adgiptzbxnzddbgfeuut/auth/users"
echo "  2. Click 'Add User' for each user"
echo "  3. Enter email and set a temporary password"
echo "  4. Note the user IDs (you'll need them)"
echo ""
echo "Option B: Via Supabase Management API"
echo "  Use the createUser API endpoint"
echo ""
echo "STEP 3: Import users data to STAGING"
echo "------------------------------------"
echo "1. Go to STAGING Supabase SQL Editor"
echo "2. Update scripts/import-users-to-staging.sql with:"
echo "   - User IDs from Step 2"
echo "   - User data from Step 1"
echo "3. Run the INSERT statements"
echo ""
echo "⚠️  Important Notes:"
echo "- User IDs must match between auth.users and public.users"
echo "- You may need to reset passwords for staging users"
echo "- Consider importing related data (leads, actions) if needed"
echo ""

